/**
 * @file main.cpp
 * @date 23.02.2018
 * @author F. Gratl
 */

#include <fstream>

#include "Simulation.h"
#include "distributed_autopas/Runtime.h"

// Declare the main AutoPas class as extern template instantiation. It is instantiated in AutoPasClass.cpp.
extern template class autopas::AutoPas<ParticleType>;

/**
 * The main function for md-flexible.
 * @param argc
 * @param argv
 * @return
 */
int main(int argc, char **argv) {
  dap::Runtime runtime(argc, argv);
  {
    MDFlexConfig configuration(argc, argv);

    // Transitional restriction while md-flexible is moved to DistributedAutoPas:
    // the current DistributedAutoPas MVP decomposes only along x and has no
    // distributed load balancing yet. Keep the legacy decomposition in the same
    // shape because it is still used by initialization / output code.
    configuration.subdivideDimension.value = {true, false, false};
    configuration.loadBalancer.value = LoadBalancerOption::none;

    auto domainDecomposition = std::make_shared<RegularGridDecomposition>(configuration);

    if (not configuration.checkpointfile.value.empty()) {
      configuration.flushParticles();
      configuration.loadParticlesFromCheckpoint(runtime.rank(), runtime.size());
    }

    // print start configuration and parallelization info
    if (runtime.isRoot()) {
      std::cout << configuration.to_string() << std::endl;
      std::cout << std::endl << "Using " << autopas::autopas_get_max_threads() << " Threads" << std::endl;
      std::cout << "DistributedAutoPas is running with " << runtime.size() << " ranks." << std::endl;
    }

    Simulation simulation(configuration, domainDecomposition, runtime);
    simulation.run();
    simulation.finalize();

    // if desired, print the configuration as a file at the end of the simulation.
    if (runtime.isRoot()) {
      if (configuration.dontCreateEndConfig.value) {
        std::ofstream configFileEnd("MDFlex_end_" + autopas::utils::Timer::getDateStamp() + ".yaml");
        if (configFileEnd.is_open()) {
          configFileEnd << "# Generated by:" << std::endl;
          configFileEnd << "# ";
          for (int i = 0; i < argc; ++i) {
            configFileEnd << argv[i] << " ";
          }
          configFileEnd << std::endl;
          configFileEnd << configuration;
          configFileEnd.close();
        }
      }
    }
  }
  return EXIT_SUCCESS;
}
