/**
 * @file main.cpp
 * @date 23.02.2018
 * @author F. Gratl
 */

#include <fstream>
#include <stdexcept>

#include "Simulation.h"
#include "distributed_autopas/Runtime.h"

// Declare the main AutoPas class as extern template instantiation. It is instantiated in AutoPasClass.cpp.
extern template class autopas::AutoPas<ParticleType>;

/**
 * The main function for md-flexible.
 * @param argc
 * @param argv
 * @return
 */
int main(int argc, char **argv) {
  dap::Runtime runtime(argc, argv);
  {
    MDFlexConfig configuration(argc, argv, runtime.isRoot());

    // DistributedAutoPas currently supports md-flexible's InvertedPressure load balancer.
    // ALL requires a different migration strategy and is intentionally not supported yet.
    if (configuration.loadBalancer.value == LoadBalancerOption::all) {
      throw std::runtime_error(
          "DistributedAutoPas does not support the ALL load balancer yet. Use InvertedPressure or None.");
    }
    if (configuration.loadBalancer.value == LoadBalancerOption::invertedPressure and
        configuration.loadBalancingInterval.value == 0) {
      throw std::runtime_error("Load balancing interval must be greater than zero.");
    }

    if (not configuration.checkpointfile.value.empty()) {
      configuration.flushParticles();
      configuration.loadParticlesFromCheckpoint(runtime.rank(), runtime.size());
    }

    // print start configuration and parallelization info
    if (runtime.isRoot()) {
      std::cout << configuration.to_string() << std::endl;
      std::cout << std::endl << "Using " << autopas::autopas_get_max_threads() << " Threads" << std::endl;
      std::cout << "DistributedAutoPas is running with " << runtime.size() << " ranks." << std::endl;
    }

    Simulation simulation(configuration, runtime);
    simulation.run();
    simulation.finalize();

    // if desired, print the configuration as a file at the end of the simulation.
    if (runtime.isRoot()) {
      if (configuration.dontCreateEndConfig.value) {
        std::ofstream configFileEnd("MDFlex_end_" + autopas::utils::Timer::getDateStamp() + ".yaml");
        if (configFileEnd.is_open()) {
          configFileEnd << "# Generated by:" << std::endl;
          configFileEnd << "# ";
          for (int i = 0; i < argc; ++i) {
            configFileEnd << argv[i] << " ";
          }
          configFileEnd << std::endl;
          configFileEnd << configuration;
          configFileEnd.close();
        }
      }
    }
  }
  return EXIT_SUCCESS;
}
